// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlvuxaxbxzsgrthpzqbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsdnV4YXhieHpzZ3J0aHB6cWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjA0NDAsImV4cCI6MjA2MDUzNjQ0MH0.-wq9WwCsEyyRjzIsmD0Sp3LlhE3PbI_87abka65XxtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);